name: Lint Swift Files
on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/lint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"
  pull_request:
    paths:
      - ".github/workflows/lint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"
jobs:
  swiftlint:
    if: '!github.event.pull_request.merged'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run SwiftLint
        run: docker run --rm -v "$PWD:$PWD" -w "$PWD" ghcr.io/realm/swiftlint:0.65.0 lint --strict
